name: 'test actions'
description: 'This is test actions.'
author: 'Tomoaki Nakagawa'
inputs:
  target:
    description: 'make target'
    default: 'build'
runs:
  using: 'node12'
  main: 'dist/index.js'
